# Generated by Django 5.1.1 on 2025-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, default='icon.png', null=True, upload_to='contacts_photo/'),
        ),
    ]
